export const RECEIVE_REPOISSUE = 'RECEIVE_REPOISSUE';
export const RECEIVE_REPOISSUE_ERROR = 'RECEIVE_REPOISSUE_ERROR';
export const RECEIVE_ISSUEDETAILS = 'RECEIVE_ISSUEDETAILS';
export const RECEIVE_ISSUEDETAILS_ERROR = 'RECEIVE_ISSUEDETAILS_ERROR';
